Simple.OData.Client.Core/Adapter/CommandFormatterBase.cs
Simple.OData.Client.Core/Fluent/CommandDetails.cs
Simple.OData.Client.Core/Fluent/FluentClientBase.cs
Simple.OData.Client.Core/Fluent/FluentCommand.cs
Simple.OData.Client.Core/Fluent/IFluentClient.cs
Simple.OData.Client.Core/ODataLiteral.cs

Difficult to write tests for this as the Northwind solution hasn't been updated to support $search. However we are using ElasticSearch as our data store and have been able to implement $search support ourselves.
It would be very useful to be able to use search in your client.
Any suggestions on the proposed request? I thought you may have a set of tests which check the urls produced?
Thanks,
Jon

Add $search Functionality.

---

Simple.OData.Client.V4.Adapter/RequestWriter.cs

On the server-side, properties in complex types were marked as ignored. When data was pushed by the client back to the server, these properties tried to map which failed. This change restricts complex type properties to those that are defined by the model.

Complex Types not ignoring properties that should be ignored.

---

Simple.OData.Client.Core/Extensions/TypeExtensions.cs
Simple.OData.Client.Tests.Core/Entities/Transport.cs

This adds parity for GetDeclared* between .Net 4.0 and .Net 4.5+ by excluding static members when using the newer TypeInfo API's. Fixes #184.

Updates TypeExtensions to skip Static Members under .Net 4.5+

---

Simple.OData.Client.Core/Utils.cs

As detailed in #192 when `Utils.TryConvert` attempts to coerce a non-nullable value type to a nullable it falls back on calling `System.Convert.ChangeType`, which fails to perform this coercion. This patch (on the v4 branch, lands cleanly in master but I've not tested there) adds a test using `Nullable.GetUnderlyingType` before the fallback `Convert.ChangeType`, which resolves this regression.

Fixes regression from 4.11 to 4.12+ with Utils.TryConvert and Nullables

---

Simple.OData.Client.V4.Adapter/ResponseReader.cs

only standard odata annotations are returned by default. If custom annotations are used, these are only returned by the Reader if ShouldIncludeAnnotation returns true.

support custom feed annotations

---

Simple.OData.Client.Core/Adapter/AdapterFactory.cs
Simple.OData.Client.Core/Adapter/BatchWriterBase.cs
Simple.OData.Client.Core/Adapter/RequestWriterBase.cs
Simple.OData.Client.Core/Adapter/ResponseReaderBase.cs
Simple.OData.Client.Core/Fluent/BoundClient.Async.cs
Simple.OData.Client.Core/Fluent/FluentClientBase.cs
Simple.OData.Client.Core/Fluent/FluentCommand.cs
Simple.OData.Client.Core/Http/RequestRunner.cs
Simple.OData.Client.Core/Http/WebRequestException.cs
Simple.OData.Client.Core/ODataClient.Async.cs
Simple.OData.Client.Core/ODataClient.Internals.cs
Simple.OData.Client.Core/Session.cs
Simple.OData.Client.V3.Adapter/BatchWriter.cs
Simple.OData.Client.V3.Adapter/RequestWriter.cs
Simple.OData.Client.V3.Adapter/ResponseReader.cs
Simple.OData.Client.V4.Adapter/BatchWriter.cs
Simple.OData.Client.V4.Adapter/RequestWriter.cs
Simple.OData.Client.V4.Adapter/ResponseReader.cs

There is no sense to return back to the same thread which was initiator of the async operation inside library.

Use ConfigureAwait(false) on all awaiting tasks

---

Simple.OData.Client.V3.Adapter/ResponseReader.cs
Simple.OData.Client.V4.Adapter/ResponseReader.cs

This is a fix to #301 based on the suggestion of @beforeyousreejesh. I tried it in my [issue demo solution](https://github.com/vojtechvit/ODataClientCacheProblemDemo) by compiling and replacing the Simple OData Client DLLs and it worked as expected - no exception is thrown anymore when a new property is added to the service model on the service side while the old service model is cached on the client.

New properties on a service don't break existing running clients

---

Simple.OData.Client.Tests.Core/ExpansionTests.cs
Simple.OData.Client.V4.Adapter/CommandFormatter.cs

Corrected command URL formatting for queries with Expand() and multiple OrderBy()/ThenBy() ordering (with and without expanded properties).
This should fix issue https://github.com/object/Simple.OData.Client/issues/313.

Fixed issue #313

---

Simple.OData.Client.Core/Adapter/RequestWriterBase.cs
Simple.OData.Client.Core/Http/RequestRunner.cs
Simple.OData.Client.Core/Http/RestVerbs.cs
Simple.OData.Client.Core/ODataUpdateMethod.cs
Simple.OData.Client.V3.Adapter/BatchWriter.cs
Simple.OData.Client.V3.Adapter/RequestWriter.cs
Simple.OData.Client.V4.Adapter/BatchWriter.cs
Simple.OData.Client.V4.Adapter/RequestWriter.cs
Solutions/.vs/config/applicationhost.config
Solutions/Simple.OData.Client.All.sln

Since this library works with OData versions v1-v4 ([as OData.org says](http://www.odata.org/libraries/)) my xamarin app was not able to create an update request, because my service doesn't implement PATCH method but MERGE. So, may be good idea to keep this method.

Backward Compatibility for update method using MERGE Http method

---

Simple.OData.Client.Core/Expressions/ODataExpression.Format.cs
Simple.OData.Client.Dynamic/ODataDynamic.cs

#355 Added support of the filter function any() to be used without parameters.
#356 Corrected the creation of FunctionExpression in ExpressionFromFunction.
Before calling DynamicODataExpression.FromFunction(), a refrence Expression must be created from the  targetName. Otherwise it will be implicitly casted to a value Expression. (Which then fails in ODataExpression.FormatCallerReference())

Fixed Issues #355 and #356

---

CommonAssemblyVersion.cs
Simple.OData.Client.Core/Fluent/FluentClientBase.cs
Simple.OData.Client.Core/Fluent/IFluentClient.cs
Simple.OData.Client.Core/ODataClient.Async.cs
Solutions/.vs/config/applicationhost.config

This is not supported:
(Set dynamicpropertycontainer for Generic Type defined in ExecuteAsArrayAsync)
`return await OdataClient.For<T>(collectionName)
.Function("ModifiedSince")
.Set(new Dictionary<string, object> { { "Date", datestring } }).ExecuteAsArrayAsync<EntityDiffDto>(CancellationToken.None) ==> .WithProperties(a=>a.ChangedProperties); <==
I modified the code to allow this in this way (optional argument)
return await OdataClient
.For<T>(collectionName)
.Function("ModifiedSince")
.Set(new Dictionary<string, object> { { "Date", datestring } }).ExecuteAsArrayAsync<EntityDiffDto>(CancellationToken.None, **nameof(EntityDiffDto.ChangedProperties)**);

Commit ExecuteAsArrayAsync Properties Support

---

ActionProviderImplementation/App.config
Simple.OData.Client.Tests.Net40/App.config
Simple.OData.Client.Tests.Net45/App.config
Simple.OData.NorthwindService/Web.config
Simple.OData.ProductService/Web.config
WebApiOData.V3.Samples/app.config

I couldn't run the integration tests as EntityFramework was trying to connect to SqlExpress, which I don't  have installed as I already have full SQL Server,
There is localdb which is installed as part Visual Studio under SQL Data Tools, so I've changed the default connection factory to use that instead

Make EF use localdb rather than SqlExpress

---

Simple.OData.Client.Core/ODataBatch.cs
Simple.OData.Client.Core/ODataClient.cs
Simple.OData.Client.IntegrationTests/BatchODataTests.cs
Simple.OData.Client.Tests.Net40/ClientSettingsTests.cs
Simple.OData.Client.Tests.Net40/Simple.OData.Client.Tests.Net40.csproj

A few of these changes felt really clunky to me because of the existing design patterns.  Like I'm trying to shoe horn in my use case to fit into the overall architecture, but I also tried to keep the changes minimal.  Integration/Unit tests are shown as examples more than anything else as they aren't able to hit any endpoints that actually provide xcsrf tokens, but when I tested this code in my specific environment where I'm able to get back tokens, it was working.

Add support for multiple requests when using ODataBatch (helps support xcsrf tokens)

---

Simple.OData.Client.Core/Adapter/AdapterFactory.cs

the protocol version is now correctly determined from the metadata document

Fixed Issue #408 wrong protocol version from metadata

---

Simple.OData.Client.Core/Adapter/AdapterFactory.cs
Simple.OData.Client.Core/Adapter/IODataModelAdapter.cs
Simple.OData.Client.Core/Adapter/ODataModelAdapterBase.cs
Simple.OData.Client.Core/MetadataCache.cs
Simple.OData.Client.Core/ODataClient.cs
Simple.OData.Client.Core/Session.cs
Simple.OData.Client.Core/Simple.OData.Client.Core.csproj
Simple.OData.Client.IntegrationTests/FindNuGetTests.cs
Simple.OData.Client.Net40/Simple.OData.Client.Net40.csproj
Simple.OData.Client.V3.Adapter/ODataAdapter.cs
Simple.OData.Client.V3.Adapter/ODataModelAdapter.cs
Simple.OData.Client.V3.Adapter/Simple.OData.Client.V3.Adapter.csproj
Simple.OData.Client.V4.Adapter/ODataAdapter.cs
Simple.OData.Client.V4.Adapter/ODataModelAdapter.cs
Simple.OData.Client.V4.Adapter/Simple.OData.Client.V4.Adapter.csproj

This PR attempts to address #249 by serializing access to the `$metadata` route per base URI. It also adds a layer of indirection for model parsing, sitting on top of the existing `IODataAdapter` layer.
Basic design:
- `MetadataCache` maintains a static internal, threadsafe dictionary of its own instances, keyed by their AbsoluteURI
- `Session` reaches into `MetadataCache` during construction if given the metadata as a string, otherwise the resolution of the metadata is deferred
- `Session` initiates the metadata resolution, and via the threadsafe `MetadataCache.GetOrAdd` method, it serializes the requests against any `$metadata` route.
- Until the initial request completes, all other requests wait.
- Once the `$metadata` request completes, the `MetadataCache` instance creates an …

Reduce $metadata lookups and model parsing

---

Simple.OData.Client.V4.Adapter/ResponseReader.cs

Strip double quoting of strings for dynamic properties

Fix for OData 7.x quoting string dynamic type values

---

src/Simple.OData.Client.Core/MetadataCache.cs
src/Simple.OData.Client.Core/Session.cs
src/Simple.OData.Client.UnitTests/Core/MetadataCacheTests.cs

fixes the bug introduced in #435 as described in #494 
Possible issues:
* The test is currently not marked as integration, but is relying on an external odata service.

fix Metadata cache for not reused settings

---

src/Simple.OData.Client.Core/Fluent/FluentClientBase.cs
src/Simple.OData.Client.Core/Fluent/IFluentClient.cs

I've developed a code generator which generates proxy class based on Simple.OData.Client
By generated code we can write followings:
```cs
Client.Customers().GetCustomerById(1).ExecuteAsSingleAsync();
```
instead of
```cs
Client.For<CustomerDto>("Customers").Function("GetCustomerById").Set(new { customerId = 1 }).ExecuteAsSingleAsync();
``` 
In my generated code, Customers() returns ```IBoundClient<CustomerDto>``` and therefor ```GetCustomerById(1).ExecuteAsSingleAsync``` has to return CustomerDto which is fine.
But imaging another method:
```cs
Client.Customers.GetCityOfCustomerById(1)
// equivalent for Client.For<CustomerDto>("Customers").Function"(GetCityOfCustomerById").Set(new { customerId = 1 }).ExecuteAsSingleAsync();
```
Which needs to return CityDto, but when I call …

Added useful methods to FluentClient

---

src/Simple.OData.Client.Core/Adapter/ResponseNode.cs
src/Simple.OData.Client.Core/Adapter/ResponseReaderBase.cs

Annotations are not included in collection navigations. Example:
```csharp
public class Parent
{
public Child[] Children { get; set; }
}
public class Child
{
}
client.For<Parent>().Expand(x => x.Children)[...];
```
The annotations are not included for each child, even if `IncludeAnnotationsInResults` is set to true. This PR fixes that.

Added annotations to child collections.

---

src/Simple.OData.Client.Core/Adapter/ResponseReaderBase.cs
src/Simple.OData.Client.IntegrationTests/BatchODataTests.cs

- Allow processing of batch requests to continue if IgnoreResourceNotFoundException property is true and batch request returns 404.
- Also removed a redundant 'else if' block. From what I can tell, an actionResponse that has a statusCode >= 400 will always have an Exception attached. So there is no need to check for a statusCode >= 400 after we have confirmed that there is no exception. 
- Added a test for the continuation of batch processing.
Ticket Link:
https://github.com/simple-odata-client/Simple.OData.Client/issues/485

Fix issue #485

---

src/Simple.OData.Client.Core/IODataClient.cs
src/Simple.OData.Client.Core/ODataClient.Async.cs
src/Simple.OData.Client.Core/ODataResponse.cs
src/Simple.OData.Client.IntegrationTests/BatchODataTests.cs
src/Simple.OData.Client.IntegrationTests/InsertODataTests.cs
src/Simple.OData.Client.V3.Adapter/ResponseReader.cs
src/Simple.OData.Client.V4.Adapter/ResponseReader.cs

When inserting data I like to use `Prefer=minimal` and just get the entity id from the `Location` or `OData-EntityId` headers. I could not find a way to do this for batch requests. For normal requests one could use `BuildRequestFor` and execute the request yourself using `IClientWithRequest` and `IClientWithResponse` to get the response.
I added a slightly easier way that also works in batch requests.

allow reading Location and OData-EntityId header from batches

---

src/Simple.OData.Client.Core/ODataClientSettings.cs
src/Simple.OData.Client.UnitTests/BasicApi/ClientReadWriteTests.cs
src/Simple.OData.Client.UnitTests/FluentApi/BatchTests.cs
src/Simple.OData.Client.UnitTests/FluentApi/LinkDynamicTests.cs
src/Simple.OData.Client.UnitTests/FluentApi/LinkTests.cs
src/Simple.OData.Client.UnitTests/FluentApi/LinkTypedTests.cs
src/Simple.OData.Client.V4.Adapter/RequestWriter.cs

This PR closes #441, closes #194
Unlinking references in OData v2 and v3 endpoints is quite different to v4 and v4.01 endpoints. While versions before v4 using the `http://host/service/$links/NavigationProperty` template, versions of v4 or v4.01 must implement this `http://host/service/Entity(id)/NavigationProperty/$ref` template to address entity references. On top of that, there are two different ways to delete **collection** of references:
1. `DELETE http://host/service/Categories(1)/Products/$ref?$id=../../Products(0)`
1. `DELETE http://host/service/Products(0)/Category/$ref`
The spec of [Odata v4.0 - 4.4](https://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part2-url-conventions/odata-v4.0-errata03-os-part2-url-conventions-complete.html#_Toc453752345) contains the …

 Add support to delete references between entities by absolute URIs

---

src/Simple.OData.Client.V4.Adapter/RequestWriter.cs

This PR makes sure that a trailing slash `/` always exists at the end of `_session.Settings.BaseUri.AbsoluteUri` when using absolute reference URIs to keep a valid URL.
Thanks @lordmampf :)

Fix possible missing slashes

---

src/Simple.OData.Client.Core/ODataClientSettings.cs
src/Simple.OData.Client.UnitTests/Core/OpenTypesTests.cs
src/Simple.OData.Client.UnitTests/Resources/OpenTypeV401.json
src/Simple.OData.Client.UnitTests/Resources/OpenTypes.xml
src/Simple.OData.Client.UnitTests/Simple.OData.Client.UnitTests.csproj
src/Simple.OData.Client.V4.Adapter/ODataExtensions.cs

When using OData v401 OpenTypes there is the ability to utilize types from a response.
The PR adds the ability to set the flag in settings for Microsoft.Odata.ODataMessageReader to enable that.
This PR duplicates #524 and resolves merge conflicts

Add ability to set ReadUntypedAsString to false

---

src/Simple.OData.Client.IntegrationTests/TripPinEntities.cs
src/Simple.OData.Client.IntegrationTests/TripPinTests.cs

unit test examples for $expand with $select on collection and 1:1 as discussed in #578 and #136
`$expand=Photo($select=Name)`
`$expand=Friends($select=UserName)`
also fixes the invalid `Person.Photos` reference

$select inside $expand example

---

src/Simple.OData.Client.Core/Adapter/RequestWriterBase.cs

Relationship deletes were not being setup correctly when batching.  This is a fix for defect https://github.com/simple-odata-client/Simple.OData.Client/issues/402.

fix for defect 402 - batch reference

---

src/Simple.OData.Client.Core/Adapter/CommandFormatterBase.cs
src/Simple.OData.Client.UnitTests/Core/StreamTests.cs

This PR fixes #645 and fixes #499 and allows adding query options (including [Custom Query Options](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#_Toc26180032)) for all cases.
It means that a user can easier create queries which would not work. On the other hand the user were never noticed about automatically removed query options before. Both options have pros and cons but I tend to the first one, because this is the correct solution: Query options should always be allowed for RESTful APIs as well as for OData APIs.
What do you think?

Add the possibility to add request query options for all cases

---

src/Simple.OData.Client.Core/Extensions/MemberInfoExtensions.cs
src/Simple.OData.Client.UnitTests/Core/TypedExpressionsTests.cs
src/Simple.OData.Client.UnitTests/Simple.OData.Client.UnitTests.csproj

This PR contains change supporting JsonPropertyNameAttribute from the [System.Text.Json](https://www.nuget.org/packages/System.Text.Json/) package. In the unit test, I purposely fully qualified the attribute instead of adding a ```using``` statement so that it was clear this was from the [System.Text.Json](https://www.nuget.org/packages/System.Text.Json/) package.  I wanted to add a test for the [JsonIgnoreAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonignoreattribute?view=netcore-3.1) however, I was not able to find the tests.  Since the attribute name is the same between [System.Text.Json](https://www.nuget.org/packages/System.Text.Json/) and [Newtonsoft.Json](https://www.nuget.org/packages/Newtonsoft.Json/) I would assume it will work without …

Add support for System.Text.Json JsonPropertyName mapping

---

src/Simple.OData.Client.Core/Cache/ITypeCache.cs
src/Simple.OData.Client.Core/Cache/TypeCache.cs
src/Simple.OData.Client.Core/Cache/TypeCacheExtensions.cs
src/Simple.OData.Client.Core/Cache/TypeCacheResolver.cs
src/Simple.OData.Client.Core/Extensions/DictionaryExtensions.cs
src/Simple.OData.Client.UnitTests/Extensions/DictionaryExtensionsTests.cs
src/Simple.OData.Client.UnitTests/Extensions/TypeCacheTests.cs
src/Simple.OData.Client.UnitTests/FluentApi/FindTests.cs
src/Simple.OData.Client.UnitTests/FluentApi/FindTypedTests.cs

Extend ToObject to check OData annotations for most appropriate type before deserializing
Extend ITypeCache with GetAnnotationsProperty/GetDerivedTypes

Automatic subtype resolution based on ODataAnnotations/TypeCache

---

src/Simple.OData.Client.Core/Cache/TypeCache.cs
src/Simple.OData.Client.Core/Simple.OData.Client.Core.csproj

Attempt to fix [#243](https://github.com/simple-odata-client/Simple.OData.Client/issues/243) [#736](https://github.com/simple-odata-client/Simple.OData.Client/issues/736) by explicitly handling conversions between Microsoft.OData.Edm.Date and System.DateTime

Handle conversion between Microsoft.OData.Edm.Date and System.DateTime

---

src/Simple.OData.Client.Core/Expressions/ODataExpression.cs
src/Simple.OData.Client.UnitTests/Core/KeyTests.cs
src/Simple.OData.Client.UnitTests/Entities/Activity.cs
src/Simple.OData.Client.UnitTests/Resources/KeyDemo.xml
src/Simple.OData.Client.UnitTests/Simple.OData.Client.UnitTests.csproj

The `ExtractLookupColumns` is only used to check if the filter statement can be interpreted as key:
https://github.com/simple-odata-client/Simple.OData.Client/blob/5d2cc4d93fdb98a93e3966d10d1ae5b038017831/src/Simple.OData.Client.Core/Fluent/FluentCommand.cs#L667
fixes #176

Do not interpret filter of nested entity or complex properties as key

---

src/Simple.OData.Client.Core/Adapter/CommandFormatterBase.cs
src/Simple.OData.Client.Core/Adapter/ICommandFormatter.cs
src/Simple.OData.Client.Core/Expressions/ODataExpression.Format.cs
src/Simple.OData.Client.Core/Fluent/BoundClient.Async.cs
src/Simple.OData.Client.Core/Fluent/BoundClient.cs
src/Simple.OData.Client.Core/Fluent/CommandDetails.cs
src/Simple.OData.Client.Core/Fluent/FluentClientBase.cs
src/Simple.OData.Client.Core/Fluent/FluentCommand.cs
src/Simple.OData.Client.Core/Fluent/FluentCommandDetails.cs
src/Simple.OData.Client.Core/Fluent/RequestBuilder.cs
src/Simple.OData.Client.Core/Fluent/ResolvedCommand.cs
src/Simple.OData.Client.Core/ODataClient.Async.cs
src/Simple.OData.Client.Core/ODataClient.Internals.cs
src/Simple.OData.Client.V3.Adapter/CommandFormatter.cs
src/Simple.OData.Client.V4.Adapter/CommandFormatter.cs

This is a rather big PR with the following goal:
- Remove Session field from FluentCommand. FluentCommand needs to be decoupled from the schema, it should be similar to SQL command before preparation, just a set of instructions that will be later mapped to OData resources and converted into an HTTP request.
- Introduce ResolvedCommand that is a served as a prepared OData command, it is transformed from a FluentCommand by applying OData schema and then mapping to actual OData resources and properties.

Introduce ResolvedCommand

---

src/Simple.OData.Client.Core/Expressions/FunctionToOperatorMapping.cs
src/Simple.OData.Client.Core/Expressions/ODataExpression.Format.cs
src/Simple.OData.Client.Core/Expressions/ODataExpression.Linq.cs
src/Simple.OData.Client.UnitTests/Core/FormatSettings.cs
src/Simple.OData.Client.UnitTests/Core/TypedExpressionsTests.cs
src/Simple.OData.Client.UnitTests/Core/TypedFilterAsKeyTests.cs

Adds support for 'in' operator introduced in OData v4.01 (https://docs.oasis-open.org/odata/new-in-odata/v4.01/cn04/new-in-odata-v4.01-cn04.html#sec_NewinOperator).
Sample:
`var command = _client.For<Product>().Filter(x => ids.Contains(x.ProductID));`
Fixes #684

Support 'in' operator introduced in OData v4.01

---

src/Simple.OData.Client.Core/Adapter/IRequestWriter.cs
src/Simple.OData.Client.Core/Adapter/RequestWriterBase.cs
src/Simple.OData.Client.Core/Fluent/FluentClientBase.cs
src/Simple.OData.Client.Core/Fluent/FluentCommand.cs
src/Simple.OData.Client.Core/Fluent/FluentCommandDetails.cs
src/Simple.OData.Client.Core/Fluent/IFluentClient.cs
src/Simple.OData.Client.Core/Fluent/RequestBuilder.cs
src/Simple.OData.Client.Core/ODataClient.Internals.cs
src/Simple.OData.Client.Core/ODataRequest.cs
src/Simple.OData.Client.UnitTests/Core/RequestWriterTests.cs
src/Simple.OData.Client.UnitTests/FluentApi/FindTests.cs

Added a WithHeaders method to allow setting arbitrary http headers to the produced http request. This is helpfull for example for setting up impersonation in CDS OData calls.

Ability to add http headers from the fluent API.

---

src/Simple.OData.Client.Core/ODataRequest.cs
src/Simple.OData.Client.UnitTests/FluentApi/FindTests.cs

@object Apologies I missed an obvious bug. I started working an Http headers for batch operations and after digging in a bit deeper I realsed I was testing against the ODataRequest object and the test passed but the headers weren't getting propagated to the actual http request. I fixed the bug and the tests. I will commit the changes for batch http headers on a separate PR.

Fixed missing HttpRequestMessage header assignment from ODataRequest.

---

src/ActionProviderImplementation/ActionProviderImplementation.csproj
src/Simple.OData.Client.Core/Expressions/ODataExpression.Linq.cs
src/Simple.OData.Client.Core/Simple.OData.Client.Core.csproj
src/Simple.OData.Client.Dynamic/Simple.OData.Client.Dynamic.csproj
src/Simple.OData.Client.UnitTests/Core/TypedExpressionsTests.cs
src/Simple.OData.Client.V3.Adapter/Simple.OData.Client.V3.Adapter.csproj
src/Simple.OData.Client.V4.Adapter/Simple.OData.Client.V4.Adapter.csproj
src/Simple.OData.NorthwindModel/Simple.OData.NorthwindModel.csproj
src/Simple.OData.NorthwindService/Simple.OData.NorthwindService.csproj
src/Simple.OData.ProductService/Simple.OData.ProductService.csproj
src/WebApiOData.V3.Samples/WebApiOData.V3.Samples.csproj
src/WebApiOData.V4.Samples/WebApiOData.V4.Samples.csproj

This pull request fix evaluation of constant expressions containing mapped properties. This change should fix #639

Fix evaluation of constant expression containing mapped properties

---

src/Simple.OData.Client.UnitTests/Core/ExpansionTests.cs
src/Simple.OData.Client.UnitTests/HelperExtensions.cs
src/Simple.OData.Client.V4.Adapter/CommandFormatter.cs

Fix for issue #801 
The SelectPathSegmentColumns had a lot of unreachable code which I removed. There was a bug in the remaining code where there was a "contains" instead of an "equals" operation so I refactored towards that. This is a regression issue from the August $expand enhancements.
A have added a test against this specific senario, it's not really a functional test so I can remove it after you review it.

Fix for issue #801

---

src/Simple.OData.Client.Core/Http/RequestRunner.cs

This PR slightly optimize the RequestExecutor call by adding `.ConfigureAwait(false)`. This also helps to avoid a deadlock when code is run synchronously using [this approach](https://stackoverflow.com/a/5097066).

Optimize RequestExecutor call

---

src/Simple.OData.Client.Core/BatchPayloadUriOption.cs
src/Simple.OData.Client.Core/Cache/TypeCache.cs
src/Simple.OData.Client.Core/ODataClientSettings.cs
src/Simple.OData.Client.Core/Simple.OData.Client.Core.csproj
src/Simple.OData.Client.Core/ValidationKinds.cs
src/Simple.OData.Client.V4.Adapter/BatchWriter.cs
src/Simple.OData.Client.V4.Adapter/ODataExtensions.cs
src/Simple.OData.Client.V4.Adapter/RequestWriter.cs
src/Simple.OData.Client.V4.Adapter/Simple.OData.Client.V4.Adapter.csproj

More info at #818 . Duplicates the enums defined in Microsoft.Data.OData in order to keep existing clients working as-is, making sure that no code path in the V3 adapter uses V4 data types.

Fix #818 Move OData v4 dependencies to the correct adapter

---

src/Simple.OData.Client.Core/Fluent/RequestBuilder.cs
src/Simple.OData.Client.Core/ODataClient.Internals.cs
src/Simple.OData.Client.Core/ODataClient.cs

The initial setup of a client from settings is expensive. There are a couple of cases that the code internally creates a client using the original settings. 
One is used to simply create a formatted command in Link/Unlink request. This was refactored to use the resolved command directly.
The other was to execute the entry interation in IterateEntriesAsync. This one was refactored to create a new client using a constructor with the client itself. It practicly copies the settings, session and request runner objects, which in turn are stateless. The only state the client it self holds as far as I can tell is batch related. I guess that's why there is a need for a different client, so that the read iteration is performed outside the batch and the sideffect inside. In any case this patch …

Refactor internal client instantiations

---

src/Simple.OData.Client.Core/EdmMetadataCache.cs
src/Simple.OData.Client.Core/Session.cs
src/Simple.OData.Client.IntegrationTests/MetadataODataTests.cs
src/Simple.OData.Client.IntegrationTests/Simple.OData.Client.IntegrationTests.csproj

The current `master` branch version has a concurrency issue during metadata cache initialization. When starting parallel requests wich a cold/empty cache, a missing double-checked lock leads to multiple, sequential $metadata endpoint calls. 
I implemented a new test to simulate this situation:
`Simple.OData.Client.Tests.MetadataODataTests.ParallelBootstrapping()`
Before fixing the issue:
After fixing the issue:

Fixed concurrency issues while initializing metadata cache

---

src/Simple.OData.Client.Core/EdmMetadataCache.cs

Unfortunately, I introduced a race condition with this pull request: #830 
The race condition occurs when 3 or more `ODataClient` instances that do not share their `ISession` instance simultaneously perform a cold-cache call. They all need to fetch metadata at the same time - here's the scenario:
- The first call works fine
- The second call as well, but this one does not release the semaphore
- Therefore, the third call starves while waiting at the "barrier" (`semaphore.WaitAsync()`)

Fix concurrency edge case / race condition

---

src/Simple.OData.Client.Core/Http/RequestRunner.cs
src/Simple.OData.Client.Core/ODataClientSettings.cs

Added SemaphoreRequestLimiter to ODataClientSettings and corresponding semaphore and semaphoreLimiter to RequestRunner. Enables the setting SemaphoreRequestLimiter which takes an int to set the limit of concurrent requests a client can run. Can prevent error 429.

Added SemaphoreRequestLimiter to ODataClientSettings
