simple-odata-client/Simple.OData.Client

- Simple.OData.Client.Core/Http/WebRequestException.cs
For logging and debugging purposes it would be great if the WebRequestException includes the uri which was requested.
> Try to include the request uri into WebRequestException

- Simple.OData.Client.Core/Utils.cs
- Simple.OData.Client.Tests.Core/ValueConversionTests.cs
This is similar to https://github.com/OData/WebApi/issues/718 so I fixed it in the same way
> Fix for #371 - Assign to compatible type

- Simple.OData.Client.Core/MetadataCache.cs
- Simple.OData.Client.Core/Session.cs
- Simple.OData.Client.Tests.Core/MetadataCacheTests.cs
- Simple.OData.Client.Tests.Core/Simple.OData.Client.Tests.Core.csproj
fixes #435 
I've also cleaned up the MetadataCache, removed all Task references and made the document readonly.
> Don't cache errors in MetadataCache

- README.md
- Simple.OData.V4.Client.nuspec
Cleaning up some text in order to help with the readability of usage information.
> Small description text typos

- src/Simple.OData.Client.Core/Adapter/ResponseNode.cs
- src/Simple.OData.Client.IntegrationTests/TripPinTests.cs
- src/Simple.OData.NorthwindService/Simple.OData.NorthwindService.csproj
- src/Simple.OData.ProductService/Simple.OData.ProductService.csproj
> Don't return null for empty collections

- src/Simple.OData.Client.UnitTests/Core/ResponseReaderV4Tests.cs
- src/Simple.OData.Client.V4.Adapter/ResponseReader.cs
> read complex response into IDictionary

- src/Simple.OData.Client.Core/Adapter/ResponseReaderBase.cs
Add annotations onto expanded entities so we can obtain subtype information.
Three failing tests, UnlinkEntry but these appear to be broken in the current v5 branch anyway
> Fix for #480, 

- src/Simple.OData.Client.Core/Fluent/MediaClient.cs
- src/Simple.OData.Client.Core/Fluent/RequestBuilder.cs
- src/Simple.OData.Client.Core/ODataClient.Async.cs
- src/Simple.OData.Client.Core/ODataClient.Internals.cs
- src/Simple.OData.Client.V4.Adapter/RequestWriter.cs
Hi Vagif,
Here are the changes which fixed my deadlock issues. All works as expected now with CRM, obviously i was getting the deadlocks only with CRM because they are on V4, and the problem was in the V4 adapter.
Regards,
Kiril
> Missing ConfigureAwait calls, causing deadlocks, added.

- src/Simple.OData.Client.UnitTests/Core/RequestWriterActionTests.cs
- src/Simple.OData.Client.UnitTests/Resources/ActionWithDerivedType.xml
- src/Simple.OData.Client.UnitTests/Simple.OData.Client.UnitTests.csproj
- src/Simple.OData.Client.V4.Adapter/RequestWriter.cs
> Call action with derived type

- NugetPack.cmd
- NugetPush.cmd
- Simple.OData.Client.nuspec
- Simple.OData.V3.Client.nuspec
- Simple.OData.V4.Client.nuspec
> Upgraded symbol publishing

- src/Simple.OData.Client.Core/Adapter/ODataAdapterFactory.cs
For my tosca plugin, I need to merge all dependencies to avoid conflict with different version of Odata.  So I've modified your project to look at executed assembly if adapter v3/4 dll was not found.
> Add capability to run with ilmerge bundling.

- src/Simple.OData.Client.V4.Adapter/RequestWriter.cs
Based on breaking changes in recent versions of odata.net, we can't use WriteValue for complex types, so I reused code for writing entities to write complex types too.
> Fixed issue related to sending complex type #617

- src/Simple.OData.Client.Core/Cache/TypeCache.cs
- src/Simple.OData.Client.Core/Http/RequestRunner.cs
- src/Simple.OData.Client.Core/Http/WebRequestException.cs
- src/Simple.OData.Client.Core/Http/WebRequestExceptionMessage.cs
- src/Simple.OData.Client.Core/ODataClientSettings.cs
- src/Simple.OData.Client.Core/ODataResponse.cs
- src/Simple.OData.Client.IntegrationTests/ErrorODataTests.cs
- src/Simple.OData.Client.IntegrationTests/TestBase.cs
- src/Simple.OData.Client.V3.Adapter/ResponseReader.cs
- src/Simple.OData.Client.V4.Adapter/ResponseReader.cs
Added option to control composition of WebRequestException message.
Suggest merging with squash.
> Issue 719 exception message

- src/Simple.OData.Client.Core/Fluent/FluentCommand.cs
- src/Simple.OData.Client.UnitTests/Core/KeyTests.cs
> Fixed alternate key with single property not being correctly mapped from filter.

- src/Simple.OData.Client.Core/Extensions/DictionaryExtensions.cs
small improvement pr #727 which fixes #622
> try to find type if not in typeCache

- src/Simple.OData.Client.Core/Extensions/DictionaryExtensions.cs
improved version of #747
Sorry for my mistake. I still have 21 tests which are failing. But these tests never reach code which I changed.
Could you please test again if the tests are now fine on your side?
> try to find type if not in typeCache v2

- src/Simple.OData.Client.Core/Adapter/CommandFormatterBase.cs
- src/Simple.OData.Client.Core/Expressions/ColumnExpression.cs
- src/Simple.OData.Client.Core/Expressions/ExpandExpression.cs
- src/Simple.OData.Client.Core/Fluent/CommandDetails.cs
- src/Simple.OData.Client.Core/Fluent/FluentClientBase.cs
- src/Simple.OData.Client.Core/Fluent/FluentCommand.cs
- src/Simple.OData.Client.Core/ODataExpandAssociation.cs
- src/Simple.OData.Client.Core/ODataExpandOptions.cs
- src/Simple.OData.Client.Core/ODataOrderByColumn.cs
- src/Simple.OData.Client.UnitTests/Core/ExpansionTests.cs
- src/Simple.OData.Client.UnitTests/Core/ODataExpandAssociationTests.cs
- src/Simple.OData.Client.V3.Adapter/CommandFormatter.cs
- src/Simple.OData.Client.V4.Adapter/CommandFormatter.cs
This pull request adds support for nested filter while expanding collections. This should fix #637.
> Enhance $expand clause to support nested filter

- src/Simple.OData.Client.Dynamic/DynamicODataEntry.cs
- src/Simple.OData.Client.Dynamic/DynamicODataExpression.cs
.NET Core 3.1 (and later) seems to use caches more aggressively as .NET 4.x while working with dynamic objects. So using of e.g. Expression.Constant(this.Value) leads to reusing of the same dynamic object in subsequent calls even if a new dynamic object is created.
Fixes #770
> Avoid using of Expression.Constant to fix reusing of dynamic objects

- src/Simple.OData.Client.Core/Expressions/ExpandExpression.cs
- src/Simple.OData.Client.Core/ODataOrderByColumn.cs
- src/Simple.OData.Client.UnitTests/Core/ExpansionTests.cs
- src/Simple.OData.Client.V4.Adapter/CommandFormatter.cs
> Fix issue while expanding children #771

- src/Simple.OData.Client.Core/Utils.cs
- src/Simple.OData.Client.UnitTests/Core/TypedFilterAsKeyTests.cs
Fixes #741 where querying on part of a compound key created an incorrect filter expression, the key count wasn't checked.
> Fix broken filter for compound keys #741

- src/Simple.OData.Client.UnitTests/Core/ExpansionTests.cs
- src/Simple.OData.Client.V4.Adapter/CommandFormatter.cs
Fixes expansion of nested properties if split into multiple lines as described in #782.
> Fix expansion of nested properties if split into multiple lines

- src/Simple.OData.Client.Core/Expressions/ODataExpression.cs
- src/Simple.OData.Client.Core/Simple.OData.Client.Core.csproj
- src/Simple.OData.Client.UnitTests/Core/ExpansionTests.cs
- src/Simple.OData.Client.UnitTests/Extensions/DictionaryExtensionsTests.cs
- src/Simple.OData.Client.V3.Adapter/Simple.OData.Client.V3.Adapter.csproj
- src/Simple.OData.Client.V4.Adapter/Simple.OData.Client.V4.Adapter.csproj
- src/Simple.OData.ProductService/App_Start/WebApiConfig.cs
- src/Simple.OData.ProductService/Controllers/ProductsController.cs
- src/Simple.OData.ProductService/Controllers/WorkTaskModelsController.cs
- src/WebApiOData.V3.Samples/Startup.cs
- src/WebApiOData.V4.Samples.Tests/FunctionV4Tests.cs
Cleanup of various build warnings including
- A reference issue that caused System.Net.Http incompatibilities
- Underlying lib obsoletions
- Test code warnings
> Cleanup of build warnings.

- src/Simple.OData.Client.V4.Adapter/ResponseReader.cs
In #809 I asked a question how delta works in this client. I did some research myself and it seemed the delta functionality is missing. This PR is to add it. I don't know the code base good enough to see if it's complete. It works for my usecase.
I noticed that there is a possibility its delta+resource. In that case resource is preferred.
> delta support

- src/Simple.OData.Client.V4.Adapter/ResponseReader.cs
Faced with similar as in #633, managed to fix it this way
> Fix for Calling a function results in ODataException

- src/Simple.OData.Client.Core/Expressions/ODataExpression.Format.cs
- src/Simple.OData.Client.IntegrationTests/TripPinTests.cs
> allow any() on collection properties like int[] or string[]
